In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing
from sklearn.compose import ColumnTransformer
import joblib

In [2]:
df = pd.read_csv(r"C:\Users\dell\Documents\Digital AI\Data Sets\insurance.csv")

In [3]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [5]:
x = ['age', 'sex', 'bmi', 'children', 'smoker', 'region']
y = ['charges']

In [6]:
x = df[x]
y = df[y]

In [7]:
x.head()

   age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

In [10]:
transform = ColumnTransformer([('One', OneHotEncoder(), [1,4,5]), ('sc', StandardScaler(), [0,2,3])], remainder='passthrough')

In [11]:
x = transform.fit_transform(x)

In [12]:
x = pd.DataFrame(x)
x.head()

     0    1    2    3    4    5    6    7         8         9        10
0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0 -1.438764 -0.453320 -0.908614
1  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0 -1.509965  0.509621 -0.078767
2  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0 -0.797954  0.383307  1.580926
3  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0 -0.441948 -1.305531 -0.908614
4  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0 -0.513149 -0.292556 -0.908614

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [17]:
model = tf.keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(11,)),
    layers.Dense(32, activation='relu'),
    layers.Dense(1)
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 64)                768
_________________________________________________________________
dense_4 (Dense)              (None, 32)                2080
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 33
=================================================================
Total params: 2,881
Trainable params: 2,881
Non-trainable params: 0
_________________________________________________________________

In [18]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss=tf.keras.losses.mean_absolute_error)

In [21]:
model.fit(x_train, y_train, epochs=200, verbose=1)

Epoch 1/200
30/30 [==============================] - 0s 2ms/step - loss: 2107.8098
Epoch 2/200
30/30 [==============================] - 0s 2ms/step - loss: 2102.0886
Epoch 3/200
30/30 [==============================] - 0s 2ms/step - loss: 2099.7917
Epoch 4/200
30/30 [==============================] - 0s 1ms/step - loss: 2096.0710
Epoch 5/200
30/30 [==============================] - 0s 2ms/step - loss: 2094.1187
Epoch 6/200
30/30 [==============================] - 0s 2ms/step - loss: 2089.4316
Epoch 7/200
30/30 [==============================] - 0s 2ms/step - loss: 2087.3169
Epoch 8/200
30/30 [==============================] - 0s 2ms/step - loss: 2084.3359
Epoch 9/200
30/30 [==============================] - 0s 2ms/step - loss: 2080.3716
Epoch 10/200
30/30 [==============================] - 0s 2ms/step - loss: 2077.1350
Epoch 11/200
30/30 [==============================] - 0s 3ms/step - loss: 2073.3699
Epoch 12/200
30/30 [==============================] - 0s 3ms/step - loss: 2070.7529
Epoch 13/200
30/30 [==============================] - 0s 2ms/step - loss: 2067.0195
Epoch 14/200
30/30 [==============================] - 0s 2ms/step - loss: 2063.8513
Epoch 15/200
30/30 [==============================] - 0s 3ms/step - loss: 2059.7158
Epoch 16/200
30/30 [==============================] - 0s 3ms/step - loss: 2056.6677
Epoch 17/200
30/30 [==============================] - 0s 3ms/step - loss: 2058.1011
Epoch 18/200
30/30 [==============================] - 0s 6ms/step - loss: 2051.1191
Epoch 19/200
30/30 [==============================] - 0s 3ms/step - loss: 2046.7618
Epoch 20/200
30/30 [==============================] - 0s 3ms/step - loss: 2043.9597
Epoch 21/200
30/30 [==============================] - 0s 3ms/step - loss: 2040.1301
Epoch 22/200
30/30 [==============================] - 0s 3ms/step - loss: 2036.4683
Epoch 23/200
30/30 [==============================] - 0s 2ms/step - loss: 2034.6617
Epoch 24/200
30/30 [==============================] - 0s 2ms/step - loss: 2032.0643
Epoch 25/200
30/30 [==============================] - 0s 8ms/step - loss: 2028.0756
Epoch 26/200
30/30 [==============================] - 0s 3ms/step - loss: 2025.5697
Epoch 27/200
30/30 [==============================] - 0s 2ms/step - loss: 2022.9194
Epoch 28/200
30/30 [==============================] - 0s 2ms/step - loss: 2019.9615
Epoch 29/200
30/30 [==============================] - 0s 1ms/step - loss: 2018.1866
Epoch 30/200
30/30 [==============================] - 0s 1ms/step - loss: 2015.2872
Epoch 31/200
30/30 [==============================] - 0s 1ms/step - loss: 2012.8147
Epoch 32/200
30/30 [==============================] - 0s 2ms/step - loss: 2013.0983
Epoch 33/200
30/30 [==============================] - 0s 2ms/step - loss: 2008.1581
Epoch 34/200
30/30 [==============================] - 0s 2ms/step - loss: 2007.6349
Epoch 35/200
30/30 [==============================] - 0s 2ms/step - loss: 2004.1270
Epoch 36/200
30/30 [==============================] - 0s 1ms/step - loss: 2000.9030
Epoch 37/200
30/30 [==============================] - 0s 1ms/step - loss: 1999.6423
Epoch 38/200
30/30 [==============================] - 0s 1ms/step - loss: 1997.4755
Epoch 39/200
30/30 [==============================] - 0s 1ms/step - loss: 1995.5381
Epoch 40/200
30/30 [==============================] - 0s 1ms/step - loss: 1993.6407
Epoch 41/200
30/30 [==============================] - 0s 1ms/step - loss: 1991.0300
Epoch 42/200
30/30 [==============================] - 0s 1ms/step - loss: 1989.1165
Epoch 43/200
30/30 [==============================] - 0s 1ms/step - loss: 1987.6062
Epoch 44/200
30/30 [==============================] - 0s 1ms/step - loss: 1984.9926
Epoch 45/200
30/30 [==============================] - 0s 2ms/step - loss: 1984.4889
Epoch 46/200
30/30 [==============================] - 0s 1ms/step - loss: 1981.0142
Epoch 47/200
30/30 [==============================] - 0s 1ms/step - loss: 1981.2405
Epoch 48/200
30/30 [==============================] - 0s 1ms/step - loss: 1979.3278
Epoch 49/200
30/30 [==============================] - 0s 1ms/step - loss: 1975.8805
Epoch 50/200
30/30 [==============================] - 0s 1ms/step - loss: 1975.7122
Epoch 51/200
30/30 [==============================] - 0s 1ms/step - loss: 1973.0414
Epoch 52/200
30/30 [==============================] - 0s 2ms/step - loss: 1970.8561
Epoch 53/200
30/30 [==============================] - 0s 2ms/step - loss: 1969.9124
Epoch 54/200
30/30 [==============================] - 0s 1ms/step - loss: 1967.9556
Epoch 55/200
30/30 [==============================] - 0s 1ms/step - loss: 1965.9791
Epoch 56/200
30/30 [==============================] - 0s 2ms/step - loss: 1965.0417
Epoch 57/200
30/30 [==============================] - 0s 1ms/step - loss: 1962.8646
Epoch 58/200
30/30 [==============================] - 0s 1ms/step - loss: 1962.0389
Epoch 59/200
30/30 [==============================] - 0s 1ms/step - loss: 1959.1038
Epoch 60/200
30/30 [==============================] - 0s 2ms/step - loss: 1958.4625
Epoch 61/200
30/30 [==============================] - 0s 2ms/step - loss: 1957.5065
Epoch 62/200
30/30 [==============================] - 0s 2ms/step - loss: 1955.6478
Epoch 63/200
30/30 [==============================] - 0s 2ms/step - loss: 1953.3422
Epoch 64/200
30/30 [==============================] - 0s 2ms/step - loss: 1952.6506
Epoch 65/200
30/30 [==============================] - 0s 2ms/step - loss: 1950.9639
Epoch 66/200
30/30 [==============================] - 0s 1ms/step - loss: 1949.4871
Epoch 67/200
30/30 [==============================] - 0s 1ms/step - loss: 1948.1161
Epoch 68/200
30/30 [==============================] - 0s 1ms/step - loss: 1947.9775
Epoch 69/200
30/30 [==============================] - 0s 1ms/step - loss: 1946.1483
Epoch 70/200
30/30 [==============================] - 0s 1ms/step - loss: 1945.4886
Epoch 71/200
30/30 [==============================] - 0s 2ms/step - loss: 1943.4093
Epoch 72/200
30/30 [==============================] - 0s 2ms/step - loss: 1941.5293
Epoch 73/200
30/30 [==============================] - 0s 2ms/step - loss: 1941.3845
Epoch 74/200
30/30 [==============================] - 0s 1ms/step - loss: 1939.3688
Epoch 75/200
30/30 [==============================] - 0s 1ms/step - loss: 1939.2485
Epoch 76/200
30/30 [==============================] - 0s 1ms/step - loss: 1937.2325
Epoch 77/200
30/30 [==============================] - 0s 1ms/step - loss: 1936.8918
Epoch 78/200
30/30 [==============================] - 0s 1ms/step - loss: 1935.9786
Epoch 79/200
30/30 [==============================] - 0s 1ms/step - loss: 1935.8756
Epoch 80/200
30/30 [==============================] - 0s 1ms/step - loss: 1933.5094
Epoch 81/200
30/30 [==============================] - 0s 2ms/step - loss: 1932.0289
Epoch 82/200
30/30 [==============================] - 0s 1ms/step - loss: 1931.4998
Epoch 83/200
30/30 [==============================] - 0s 1ms/step - loss: 1930.0485
Epoch 84/200
30/30 [==============================] - 0s 1ms/step - loss: 1928.2830
Epoch 85/200
30/30 [==============================] - 0s 2ms/step - loss: 1927.5544
Epoch 86/200
30/30 [==============================] - 0s 1ms/step - loss: 1927.0034
Epoch 87/200
30/30 [==============================] - 0s 3ms/step - loss: 1927.6005
Epoch 88/200
30/30 [==============================] - 0s 2ms/step - loss: 1924.7158
Epoch 89/200
30/30 [==============================] - 0s 6ms/step - loss: 1923.9600
Epoch 90/200
30/30 [==============================] - 0s 2ms/step - loss: 1922.6565
Epoch 91/200
30/30 [==============================] - 0s 1ms/step - loss: 1922.1095
Epoch 92/200
30/30 [==============================] - 0s 1ms/step - loss: 1920.1283
Epoch 93/200
30/30 [==============================] - 0s 1ms/step - loss: 1919.7111
Epoch 94/200
30/30 [==============================] - 0s 1ms/step - loss: 1920.8079
Epoch 95/200
30/30 [==============================] - 0s 2ms/step - loss: 1919.3855
Epoch 96/200
30/30 [==============================] - 0s 3ms/step - loss: 1918.1340
Epoch 97/200
30/30 [==============================] - 0s 3ms/step - loss: 1916.3395: 0s - loss: 1844.30
Epoch 98/200

30/30 [==============================] - 0s 2ms/step - loss: 1918.2401
Epoch 99/200
30/30 [==============================] - 0s 1ms/step - loss: 1916.6333
Epoch 100/200
30/30 [==============================] - 0s 1ms/step - loss: 1914.9463
Epoch 101/200
30/30 [==============================] - 0s 2ms/step - loss: 1913.6022
Epoch 102/200
30/30 [==============================] - 0s 2ms/step - loss: 1914.0881
Epoch 103/200
30/30 [==============================] - 0s 2ms/step - loss: 1912.1772
Epoch 104/200
30/30 [==============================] - 0s 2ms/step - loss: 1911.4065
Epoch 105/200
30/30 [==============================] - 0s 1ms/step - loss: 1912.5282
Epoch 106/200
30/30 [==============================] - 0s 2ms/step - loss: 1910.7087
Epoch 107/200
30/30 [==============================] - 0s 2ms/step - loss: 1909.7432
Epoch 108/200
30/30 [==============================] - 0s 3ms/step - loss: 1911.0023
Epoch 109/200
30/30 [==============================] - 0s 3ms/step - loss: 1907.2040
Epoch 110/200
30/30 [==============================] - 0s 3ms/step - loss: 1906.5573
Epoch 111/200
30/30 [==============================] - 0s 1ms/step - loss: 1907.7461
Epoch 112/200
30/30 [==============================] - 0s 1ms/step - loss: 1906.4727
Epoch 113/200
30/30 [==============================] - 0s 1ms/step - loss: 1906.1393
Epoch 114/200
30/30 [==============================] - 0s 1ms/step - loss: 1904.1792
Epoch 115/200
30/30 [==============================] - 0s 2ms/step - loss: 1904.0912
Epoch 116/200
30/30 [==============================] - 0s 1ms/step - loss: 1903.2062
Epoch 117/200
30/30 [==============================] - 0s 2ms/step - loss: 1903.8063
Epoch 118/200
30/30 [==============================] - 0s 1ms/step - loss: 1902.1920
Epoch 119/200
30/30 [==============================] - 0s 1ms/step - loss: 1901.2057
Epoch 120/200
30/30 [==============================] - 0s 1ms/step - loss: 1901.8447
Epoch 121/200
30/30 [==============================] - 0s 2ms/step - loss: 1900.2577
Epoch 122/200
30/30 [==============================] - 0s 3ms/step - loss: 1902.8848
Epoch 123/200
30/30 [==============================] - 0s 1ms/step - loss: 1899.9825
Epoch 124/200
30/30 [==============================] - 0s 1ms/step - loss: 1900.5497
Epoch 125/200
30/30 [==============================] - 0s 2ms/step - loss: 1899.5275
Epoch 126/200
30/30 [==============================] - 0s 2ms/step - loss: 1898.4712
Epoch 127/200
30/30 [==============================] - 0s 1ms/step - loss: 1897.6002
Epoch 128/200
30/30 [==============================] - 0s 1ms/step - loss: 1897.9307
Epoch 129/200
30/30 [==============================] - 0s 1ms/step - loss: 1896.9467
Epoch 130/200
30/30 [==============================] - 0s 2ms/step - loss: 1895.7444
Epoch 131/200
30/30 [==============================] - 0s 1ms/step - loss: 1895.9303
Epoch 132/200
30/30 [==============================] - 0s 1ms/step - loss: 1894.2427
Epoch 133/200
30/30 [==============================] - 0s 1ms/step - loss: 1895.5677
Epoch 134/200
30/30 [==============================] - 0s 1ms/step - loss: 1893.4734
Epoch 135/200
30/30 [==============================] - 0s 2ms/step - loss: 1892.6035
Epoch 136/200
30/30 [==============================] - 0s 1ms/step - loss: 1895.2896
Epoch 137/200
30/30 [==============================] - 0s 1ms/step - loss: 1892.4337
Epoch 138/200
30/30 [==============================] - 0s 1ms/step - loss: 1892.0051
Epoch 139/200
30/30 [==============================] - 0s 1ms/step - loss: 1891.7233
Epoch 140/200
30/30 [==============================] - 0s 1ms/step - loss: 1891.3018
Epoch 141/200
30/30 [==============================] - 0s 1ms/step - loss: 1890.6375
Epoch 142/200
30/30 [==============================] - 0s 1ms/step - loss: 1889.8358
Epoch 143/200
30/30 [==============================] - 0s 1ms/step - loss: 1889.3149
Epoch 144/200
30/30 [==============================] - 0s 1ms/step - loss: 1889.2378
Epoch 145/200
30/30 [==============================] - 0s 1ms/step - loss: 1888.1194
Epoch 146/200
30/30 [==============================] - 0s 1ms/step - loss: 1888.3406
Epoch 147/200
30/30 [==============================] - 0s 1ms/step - loss: 1888.2947
Epoch 148/200
30/30 [==============================] - 0s 1ms/step - loss: 1887.4807
Epoch 149/200
30/30 [==============================] - 0s 2ms/step - loss: 1886.1615
Epoch 150/200
30/30 [==============================] - 0s 1ms/step - loss: 1885.9036
Epoch 151/200
30/30 [==============================] - 0s 1ms/step - loss: 1886.2460
Epoch 152/200
30/30 [==============================] - 0s 1ms/step - loss: 1886.3798
Epoch 153/200
30/30 [==============================] - 0s 1ms/step - loss: 1884.0676
Epoch 154/200
30/30 [==============================] - 0s 1ms/step - loss: 1883.4795
Epoch 155/200
30/30 [==============================] - 0s 1ms/step - loss: 1883.1776
Epoch 156/200
30/30 [==============================] - 0s 2ms/step - loss: 1882.9795
Epoch 157/200
30/30 [==============================] - 0s 2ms/step - loss: 1882.2358
Epoch 158/200
30/30 [==============================] - 0s 1ms/step - loss: 1883.9353
Epoch 159/200
30/30 [==============================] - 0s 1ms/step - loss: 1882.3099
Epoch 160/200
30/30 [==============================] - 0s 2ms/step - loss: 1881.1489
Epoch 161/200
30/30 [==============================] - 0s 2ms/step - loss: 1881.5132
Epoch 162/200
30/30 [==============================] - 0s 2ms/step - loss: 1882.7123
Epoch 163/200
30/30 [==============================] - 0s 2ms/step - loss: 1881.2667
Epoch 164/200
30/30 [==============================] - 0s 1ms/step - loss: 1880.4000
Epoch 165/200
30/30 [==============================] - 0s 1ms/step - loss: 1881.5150
Epoch 166/200
30/30 [==============================] - 0s 1ms/step - loss: 1879.8894
Epoch 167/200
30/30 [==============================] - 0s 1ms/step - loss: 1879.3333
Epoch 168/200
30/30 [==============================] - 0s 1ms/step - loss: 1879.3889
Epoch 169/200
30/30 [==============================] - 0s 1ms/step - loss: 1879.1023
Epoch 170/200
30/30 [==============================] - 0s 1ms/step - loss: 1877.6511
Epoch 171/200
30/30 [==============================] - 0s 2ms/step - loss: 1879.5706
Epoch 172/200
30/30 [==============================] - 0s 1ms/step - loss: 1878.4987
Epoch 173/200
30/30 [==============================] - 0s 1ms/step - loss: 1879.0477
Epoch 174/200
30/30 [==============================] - 0s 1ms/step - loss: 1877.9846
Epoch 175/200
30/30 [==============================] - 0s 2ms/step - loss: 1875.9371
Epoch 176/200
30/30 [==============================] - 0s 1ms/step - loss: 1875.7708
Epoch 177/200
30/30 [==============================] - 0s 1ms/step - loss: 1876.4430
Epoch 178/200
30/30 [==============================] - 0s 2ms/step - loss: 1875.1902
Epoch 179/200
30/30 [==============================] - 0s 1ms/step - loss: 1874.4347
Epoch 180/200
30/30 [==============================] - 0s 1ms/step - loss: 1873.8815
Epoch 181/200
30/30 [==============================] - 0s 2ms/step - loss: 1874.5076
Epoch 182/200
30/30 [==============================] - 0s 2ms/step - loss: 1875.1259
Epoch 183/200
30/30 [==============================] - 0s 1ms/step - loss: 1873.2629
Epoch 184/200
30/30 [==============================] - 0s 1ms/step - loss: 1874.4532
Epoch 185/200
30/30 [==============================] - 0s 1ms/step - loss: 1872.4005
Epoch 186/200
30/30 [==============================] - 0s 1ms/step - loss: 1872.3420
Epoch 187/200
30/30 [==============================] - 0s 1ms/step - loss: 1873.0690
Epoch 188/200
30/30 [==============================] - 0s 1ms/step - loss: 1872.1185
Epoch 189/200
30/30 [==============================] - 0s 1ms/step - loss: 1871.0350
Epoch 190/200
30/30 [==============================] - 0s 2ms/step - loss: 1871.6715
Epoch 191/200
30/30 [==============================] - 0s 2ms/step - loss: 1870.9048
Epoch 192/200
30/30 [==============================] - 0s 2ms/step - loss: 1871.3157
Epoch 193/200
30/30 [==============================] - 0s 2ms/step - loss: 1870.7488
Epoch 194/200

30/30 [==============================] - 0s 1ms/step - loss: 1871.6355
Epoch 195/200
30/30 [==============================] - 0s 1ms/step - loss: 1870.8268
Epoch 196/200
30/30 [==============================] - 0s 1ms/step - loss: 1869.2670
Epoch 197/200
30/30 [==============================] - 0s 1ms/step - loss: 1869.2673
Epoch 198/200
30/30 [==============================] - 0s 1ms/step - loss: 1869.2107
Epoch 199/200
30/30 [==============================] - 0s 1ms/step - loss: 1872.9525
Epoch 200/200
30/30 [==============================] - 0s 2ms/step - loss: 1869.2255

In [22]:
model.evaluate(x_test,y_test)

13/13 [==============================] - 0s 2ms/step - loss: 2015.2200

2015.219970703125

In [23]:
model.predict(x_test)

array([[ 1705.0548],
       [11639.866 ],
       [16005.634 ],
       [11229.685 ],
       [ 4392.0366],
       [21737.902 ],
       [12890.091 ],
       [ 2198.1467],
       [ 5143.9634],
       [ 6889.894 ],
       [ 9178.16  ],
       [ 5022.7476],
       [49372.023 ],
       [ 7515.966 ],
       [36659.465 ],
       [14371.94  ],
       [ 7237.3853],
       [ 2695.711 ],
       [ 3487.1584],
       [10971.663 ],
       [ 9861.144 ],
       [34749.742 ],
       [13360.337 ],
       [13337.883 ],
       [ 8840.368 ],
       [21227.793 ],
       [10253.663 ],
       [ 9093.971 ],
       [ 3082.4392],
       [ 2715.8706],
       [52795.844 ],
       [ 8261.869 ],
       [ 7076.289 ],
       [10000.297 ],
       [42328.367 ],
       [ 4551.8003],
       [25222.018 ],
       [ 3965.3008],
       [59393.7   ],
       [ 2692.6072],
       [ 8409.56  ],
       [ 1631.5768],
       [ 3231.7312],
       [ 2815.219 ],
       [37017.97  ],
       [ 3910.5818],
       [ 9876.46  ],
       [ 6519.2812],
       [10346.156 ],
       [ 8683.773 ],
       [ 8427.638 ],
       [14336.103 ],
       [ 3983.087 ],
       [ 4446.25  ],
       [10113.341 ],
       [29626.898 ],
       [ 6452.8813],
       [ 3362.9055],
       [ 6206.899 ],
       [24278.398 ],
       [ 1268.2114],
       [ 4416.1035],
       [ 8595.081 ],
       [ 2216.0923],
       [ 2352.736 ],
       [ 5110.1577],
       [37120.844 ],
       [13754.47  ],
       [ 6250.696 ],
       [ 3553.5488],
       [14191.097 ],
       [ 2707.7507],
       [ 7422.0874],
       [ 1823.3457],
       [12140.413 ],
       [26109.98  ],
       [ 1253.9517],
       [11443.894 ],
       [39357.125 ],
       [ 9240.099 ],
       [ 3885.9258],
       [13026.737 ],
       [ 5920.1987],
       [ 1686.4827],
       [ 2463.4807],
       [ 8167.3647],
       [ 3608.0173],
       [ 8489.653 ],
       [ 8502.921 ],
       [ 8501.481 ],
       [ 6170.5083],
       [55776.664 ],
       [13228.369 ],
       [ 2458.9485],
       [ 9610.499 ],
       [34294.273 ],
       [ 8622.03  ],
       [ 1628.4415],
       [ 1671.0266],
       [11681.097 ],
       [ 2750.0918],
       [ 6318.662 ],
       [ 1625.4607],
       [ 1810.4902],
       [12957.073 ],
       [ 8525.265 ],
       [11535.851 ],
       [ 3367.4539],
       [ 8301.405 ],
       [18512.137 ],
       [ 5755.604 ],
       [ 7189.8057],
       [ 1968.4775],
       [ 6961.767 ],
       [ 2834.8591],
       [35643.36  ],
       [ 4475.554 ],
       [30197.113 ],
       [10190.87  ],
       [ 4416.2676],
       [ 2700.0671],
       [ 2605.6057],
       [ 1618.1986],
       [ 8932.538 ],
       [ 5451.523 ],
       [11107.339 ],
       [14357.809 ],
       [26579.352 ],
       [ 8537.675 ],
       [ 6676.3477],
       [ 5980.687 ],
       [ 7388.8066],
       [ 7628.8145],
       [26758.182 ],
       [12564.499 ],
       [34462.08  ],
       [12635.407 ],
       [13149.107 ],
       [ 4609.5317],
       [10975.276 ],
       [21700.023 ],
       [44541.664 ],
       [14247.935 ],
       [22762.998 ],
       [43000.562 ],
       [10798.7   ],
       [46532.14  ],
       [ 9599.979 ],
       [14682.719 ],
       [ 2702.7175],
       [35719.688 ],
       [15535.627 ],
       [10547.76  ],
       [ 1706.4725],
       [ 2676.808 ],
       [ 4933.348 ],
       [15714.202 ],
       [13675.645 ],
       [11785.674 ],
       [ 7724.7246],
       [ 2130.0784],
       [11838.202 ],
       [11266.993 ],
       [ 4354.948 ],
       [ 7324.5884],
       [ 4035.0522],
       [ 1641.28  ],
       [31369.885 ],
       [ 5464.8916],
       [ 3899.735 ],
       [ 4572.2944],
       [ 3308.924 ],
       [ 8258.741 ],
       [13348.326 ],
       [ 8506.327 ],
       [ 9919.064 ],
       [ 3436.0933],
       [ 8260.973 ],
       [26134.67  ],
       [ 6187.4033],
       [14006.042 ],
       [ 2195.5784],
       [ 4344.826 ],
       [ 8736.955 ],
       [ 9583.097 ],
       [ 3590.2522],
       [24334.625 ],
       [13251.714 ],
       [25235.367 ],
       [14048.032 ],
       [40348.016 ],
       [ 8015.607 ],
       [ 3698.04  ],
       [10169.52  ],
       [18176.35  ],
       [22209.941 ],
       [49996.36  ],
       [ 5800.5957],
       [10963.1045],
       [ 2165.4475],
       [13551.854 ],
       [ 6624.9062],
       [27301.59  ],
       [ 2199.6365],
       [ 1618.7891],
       [ 5503.657 ],
       [ 2089.3967],
       [56739.703 ],
       [12027.168 ],
       [33908.31  ],
       [36284.29  ],
       [ 1512.4471],
       [ 7413.6484],
       [11799.938 ],
       [ 2212.8325],
       [ 3184.8167],
       [ 5473.76  ],
       [12439.419 ],
       [35745.7   ],
       [14603.897 ],
       [ 4163.9907],
       [13848.411 ],
       [ 7141.6504],
       [10786.827 ],
       [34137.41  ],
       [ 9381.102 ],
       [ 3864.8098],
       [10946.454 ],
       [35618.945 ],
       [11183.481 ],
       [10193.008 ],
       [12277.415 ],
       [ 8820.058 ],
       [ 8781.187 ],
       [49961.473 ],
       [30561.78  ],
       [ 9847.403 ],
       [20901.81  ],
       [22389.66  ],
       [ 6018.4775],
       [12946.402 ],
       [45914.816 ],
       [ 2471.8967],
       [21530.23  ],
       [ 7139.972 ],
       [13138.571 ],
       [44331.61  ],
       [ 8219.071 ],
       [ 7161.7104],
       [12187.251 ],
       [ 3748.917 ],
       [10092.351 ],
       [ 8016.7617],
       [ 1821.3792],
       [ 6177.64  ],
       [ 5209.165 ],
       [ 5399.305 ],
       [ 4996.1377],
       [ 1750.0083],
       [10859.437 ],
       [ 3959.79  ],
       [14120.651 ],
       [ 7230.787 ],
       [21484.133 ],
       [ 8503.901 ],
       [ 1642.5939],
       [14826.601 ],
       [ 1835.4989],
       [11720.524 ],
       [12660.919 ],
       [ 3081.2502],
       [ 4545.15  ],
       [10094.369 ],
       [33696.71  ],
       [12246.696 ],
       [33134.14  ],
       [55538.21  ],
       [19418.953 ],
       [ 2204.3394],
       [18110.389 ],
       [ 4806.2905],
       [10075.402 ],
       [12644.081 ],
       [ 2020.4015],
       [54012.58  ],
       [ 9185.745 ],
       [10595.4   ],
       [ 5702.562 ],
       [ 4716.5015],
       [ 5546.3374],
       [25274.088 ],
       [ 3652.4358],
       [12947.445 ],
       [11827.28  ],
       [ 4707.7075],
       [11054.338 ],
       [22383.172 ],
       [ 5905.9946],
       [ 3763.7266],
       [ 1633.8479],
       [13498.821 ],
       [ 7929.281 ],
       [12425.897 ],
       [ 7334.7007],
       [ 4514.1978],
       [ 8323.218 ],
       [11930.993 ],
       [13476.57  ],
       [42386.625 ],
       [30395.992 ],
       [15002.856 ],
       [16857.96  ],
       [ 3052.389 ],
       [ 6465.8276],
       [ 6608.4937],
       [15606.75  ],
       [ 9105.7705],
       [ 4517.984 ],
       [25465.488 ],
       [ 1534.7485],
       [ 8292.104 ],
       [ 2906.388 ],
       [ 8802.341 ],
       [13902.013 ],
       [29980.012 ],
       [12094.614 ],
       [ 7747.8696],
       [ 9341.567 ],
       [ 2315.4727],
       [ 2031.8206],
       [ 8499.864 ],
       [ 2266.2156],
       [54663.4   ],
       [12253.924 ],
       [ 6388.9653],
       [13019.891 ],
       [10698.421 ],
       [ 6568.2485],
       [ 9415.788 ],
       [23871.78  ],
       [ 4325.425 ],
       [10360.149 ],
       [ 4746.763 ],
       [ 8797.489 ],
       [ 1821.4749],
       [ 8398.772 ],
       [ 2114.1619],
       [25592.46  ],
       [ 5979.883 ],
       [ 6378.563 ],
       [ 4891.5977],
       [ 7014.026 ],
       [ 5000.932 ],
       [15670.454 ],
       [ 1697.3904],
       [ 1626.3308],
       [11639.129 ],
       [11372.84  ],
       [ 7337.2026],
       [ 4559.544 ],
       [12737.791 ],
       [ 6307.7065],
       [ 8563.98  ],
       [ 3061.3386],
       [ 8349.718 ],
       [13159.042 ],
       [ 4647.7456],
       [18312.7   ],
       [ 7270.409 ],
       [26794.777 ],
       [ 4669.708 ],
       [ 1696.3013],
       [ 2028.3088],
       [13942.289 ],
       [ 8953.353 ],
       [16587.422 ],
       [30697.434 ],
       [10385.274 ],
       [14647.102 ],
       [12018.348 ],
       [ 4738.5415],
       [ 1717.311 ],
       [ 1508.3867],
       [11059.267 ],
       [ 2378.1619],
       [12960.694 ],
       [33476.89  ],
       [ 2155.9734],
       [ 5986.1523],
       [31926.156 ],
       [ 8238.843 ],
       [ 8989.738 ],
       [ 5439.2334],
       [22328.012 ],
       [ 2848.9255],
       [ 6834.849 ],
       [ 6265.322 ],
       [ 2194.2253],
       [46635.74  ],
       [ 3385.3337],
       [ 2888.6958],
       [10215.409 ]], dtype=float32)

In [24]:
model.predict(x_test[99:100])

array([[11681.099]], dtype=float32)

In [25]:
x_test[99:100]

       0    1    2    3    4    5    6    7         8         9        10
547  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.053277  2.630716  0.751079

In [26]:
y_test[99:100]

       charges
547  11538.421

In [27]:
model.save('insurance_model.h5')

In [28]:
joblib.dump(transform, 'Insurance_model_transform.h5')

['Insurance_model_transform.h5']